In [1]:
import requests 
import os 
import shutil 
import pandas as pd

In [2]:
from bs4 import BeautifulSoup

In [3]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

## 历届MVP数据

### 可修改字段：年份

In [9]:
#注意左闭右开
years = list(range(1992,2021))

In [35]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"
for year in years:
    url = url_start.format(year)
    data = requests.get(url)
    with open("mvp/{}.html".format(year),"w+",encoding='utf-8') as f:
        f.write(data.text)
    time.sleep(1)

In [11]:
dfs = []
for year in years:
    page = open("mvp/{}.html".format(year),encoding='utf-8')
    soup = BeautifulSoup(page,'lxml')
    # soup.find('tr', class_="over_header")
    mvp_table = soup.find_all(id="mvp")[0]
    mvp_df = pd.read_html(str(mvp_table))[0]
    mvp_df["Year"] = year
    dfs.append(mvp_df)
    page.close()

In [12]:
mvps = pd.concat(dfs)
mvps.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 439 entries, 0 to 11
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   (Unnamed: 0_level_0, Rank)    439 non-null    object
 1   (Unnamed: 1_level_0, Player)  439 non-null    object
 2   (Unnamed: 2_level_0, Age)     439 non-null    int64
 3   (Unnamed: 3_level_0, Tm)      439 non-null    object
 4   (Voting, First)               439 non-null    float64
 5   (Voting, Pts Won)             439 non-null    float64
 6   (Voting, Pts Max)             439 non-null    int64
 7   (Voting, Share)               439 non-null    float64
 8   (Unnamed: 8_level_0, G)       439 non-null    int64
 9   (Per Game, MP)                439 non-null    float64
 10  (Per Game, PTS)               439 non-null    float64
 11  (Per Game, TRB)               439 non-null    float64
 12  (Per Game, AST)               439 non-null    float64
 13  (Per Game, STL)               439 non-null    float64
 14  (Per Game, BLK)               439 non-null    float64
 15  (Shooting, FG%)               439 non-null    float64
 16  (Shooting, 3P%)               428 non-null    float64
 17  (Shooting, FT%)               439 non-null    float64
 18  (Advanced, WS)                439 non-null    float64
 19  (Advanced, WS/48)             439 non-null    float64
 20  (Year, )                      439 non-null    int64
dtypes: float64(14), int64(4), object(3)
memory usage: 75.5+ KB

In [13]:
mvps.head(20)

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Rank             Player                Age
0                   1     Michael Jordan                 28
1                   2      Clyde Drexler                 29
2                   3     David Robinson                 26
3                   4        Karl Malone                 28
4                   5      Patrick Ewing                 29
5                   6       Chris Mullin                 28
6                   7         Mark Price                 27
7                   8       Tim Hardaway                 25
8                   9     Scottie Pippen                 26
9                  10      Dennis Rodman                 30
10                 11     Brad Daugherty                 26
11                12T    Charles Barkley                 28
12                12T      John Stockton                 29
13                 14         Larry Bird                 35
14                 15      Kevin Johnson                 25
15                16T      Danny Manning                 25
16                16T    Detlef Schrempf                 29
0                   1    Charles Barkley                 29
1                   2    Hakeem Olajuwon                 30
2                   3     Michael Jordan                 29

   Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                   Tm  First Pts Won Pts Max  Share                  G
0                 CHI   80.0   900.0     960  0.938                 80
1                 POR   12.0   561.0     960  0.584                 76
2                 SAS    2.0   337.0     960  0.351                 68
3                 UTA    1.0   262.0     960  0.273                 81
4                 NYK    0.0   100.0     960  0.104                 82
5                 GSW    0.0    81.0     960  0.084                 81
6                 CLE    0.0    66.0     960  0.069                 72
7                 GSW    0.0    64.0     960  0.067                 81
8                 CHI    1.0    32.0     960  0.033                 82
9                 DET    0.0    26.0     960  0.027                 82
10                CLE    0.0    24.0     960  0.025                 73
11                PHI    0.0    18.0     960  0.019                 75
12                UTA    0.0    18.0     960  0.019                 82
13                BOS    0.0     3.0     960  0.003                 45
14                PHO    0.0     2.0     960  0.002                 78
15                LAC    0.0     1.0     960  0.001                 82
16                IND    0.0     1.0     960  0.001                 80
0                 PHO   59.0   835.0     980  0.852                 76
1                 HOU   22.0   647.0     980  0.660                 82
2                 CHI   13.0   565.0     980  0.577                 78

   Per Game  ...                       Shooting               Advanced         \
         MP  ...   TRB   AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0      38.8  ...   6.4   6.1  2.3  0.9    0.519  0.270  0.832     17.7  0.274
1      36.2  ...   6.6   6.7  1.8  0.9    0.470  0.337  0.794     12.8  0.223
2      37.7  ...  12.2   2.7  2.3  4.5    0.551  0.125  0.701     13.9  0.260
3      37.7  ...  11.2   3.0  1.3  0.6    0.526  0.176  0.778     15.1  0.237
4      38.4  ...  11.2   1.9  1.1  3.0    0.522  0.167  0.738     13.0  0.198
5      41.3  ...   5.6   3.5  2.1  0.8    0.524  0.366  0.833     10.8  0.155
6      29.7  ...   2.4   7.4  1.3  0.2    0.488  0.387  0.947      9.1  0.205
7      41.1  ...   3.8  10.0  2.0  0.2    0.461  0.338  0.766      9.2  0.132
8      38.6  ...   7.7   7.0  1.9  1.1    0.506  0.200  0.760     12.7  0.192
9      40.3  ...  18.7   2.3  0.8  0.9    0.539  0.317  0.600     12.6  0.183
10     36.2  ...  10.4   3.6  0.9  1.1    0.570  0.000  0.777     11.7  0.213
11     38.4  ...  11.1   4.1  1.8  0.6    0.552  0.234  0.695     12.3  0.205
12     36.6  ...   3.3  13.7  3.0  0.3    0.482  0.407  0.842     13.4  0.215
13     36.9  ...   9.6   6.8  0.9  0.7    0.466  0.406  0.926      5.5  0.159
14     37.2  ...   3.7  10.7  1.5  0.3    0.479  0.217  0.807     10.0  0.165
15     35.4  ...   6.9   3.5  1.6  1.5    0.542  0.000  0.725      9.8  0.162
16     32.6  ...   9.6   3.9  0.8  0.5    0.536  0.324  0.828      9.8  0.181
0      37.6  ...  12.2   5.1  1.6  1.0    0.520  0.305  0.765     14.4  0.242
1      39.5  ...  13.0   3.5  1.8  4.2    0.529  0.000  0.779     15.8  0.234
2      39.3  ...   6.7   5.5  2.8  0.8    0.495  0.352  0.837     17.2  0.270

    Year

0   1992
1   1992
2   1992
3   1992
4   1992
5   1992
6   1992
7   1992
8   1992
9   1992
10  1992
11  1992
12  1992
13  1992
14  1992
15  1992
16  1992
0   1993
1   1993
2   1993

[20 rows x 21 columns]

In [14]:
mvps.to_csv("mvps.csv")

## 所有球员数据

### 可修改字段：webdriver 地址

In [5]:
driver = webdriver.Chrome(executable_path='C:/Program Files/Google/Chrome/Application/chromedriver.exe')

C:\Users\jyq\AppData\Local\Temp\ipykernel_30336\2186733188.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='C:/Program Files/Google/Chrome/Application/chromedriver.exe')

In [6]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

In [80]:
for year in years:
    url = player_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("player/{}.html".format(year), "w+", encoding='utf-8') as f:
        f.write(data.text)
    
    time.sleep(1)

In [7]:
for year in years:
    url = player_stats_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(1)
    
    with open("player/{}.html".format(year), "w+", encoding='utf-8') as f:
        f.write(driver.page_source)

In [10]:
dfs2 = []
for year in years:
    page = open("player/{}.html".format(year),encoding='utf-8')
    soup = BeautifulSoup(page,'lxml')
    # soup.find('tr', class_="over_header")
    player_table = soup.find_all(id="per_game_stats")[0]
    player_df = pd.read_html(str(player_table))[0]
    player_df["Year"] = year
    dfs2.append(player_df)
    page.close()

In [11]:
players = pd.concat(dfs2)

In [15]:
players.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,23,POR,71,1,13.2,2.5,5.1,...,1.1,2.5,3.7,0.4,0.4,0.2,0.9,1.9,6.1,1992
1,2,Mahmoud Abdul-Rauf,PG,22,DEN,81,11,19.0,4.4,10.4,...,0.3,1.1,1.4,2.4,0.5,0.0,1.4,1.6,10.3,1992
2,3,Mark Acres,C,29,ORL,68,6,13.6,1.1,2.2,...,1.4,2.3,3.7,0.3,0.4,0.2,0.5,2.1,3.1,1992
3,4,Michael Adams,PG,29,WSB,78,78,35.8,6.2,15.8,...,0.7,3.2,4.0,7.6,1.9,0.1,2.7,2.1,18.1,1992
4,5,Rafael Addison,SF,27,NJN,76,8,15.5,2.5,5.7,...,0.9,1.3,2.2,0.9,0.4,0.4,0.6,1.4,5.8,1992

In [13]:
players.to_csv("players.csv")

## 球队数据

In [83]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [85]:
for year in years:
    url = team_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("team/{}.html".format(year), "w+", encoding='utf-8') as f:
        f.write(data.text)
        
    time.sleep(1)

In [86]:
dfs = []
for year in years:
    with open("team/{}.html".format(year)) as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    # soup.find('tr', class_="thead").decompose()
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)
    
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)

In [87]:
teams = pd.concat(dfs)

In [89]:
teams.head()

,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,1992,Atlantic Division
1,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics*
2,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks*
3,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets*
4,38,44,.463,13.0,105.0,109.2,-3.94,1992,Miami Heat*

In [90]:
teams.to_csv("teams.csv")